In [4]:
import numpy as np

np.arange(0,12,3)

array([0, 3, 6, 9])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(5)

array([9.94953635e-01, 9.05036966e-05, 7.52722673e-01, 4.66139632e-01,
       7.74722827e-01])

In [11]:
arr = np.arange(0,11)

print(arr)

arr[5]

[ 0  1  2  3  4  5  6  7  8  9 10]


5

In [12]:
#broadcasting

arr[0:5] = 100

arr 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
arr_2d[2][1]

40

In [16]:
print(arr_2d[1,2])
arr_2d[2,2]


30


45

In [17]:
arr_2d[2]

array([35, 40, 45])

In [20]:
#conditional selection

arrnew = np.arange(1,11)
print(arrnew)

boolarr = arrnew > 5

print(boolarr)

boolarr


[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [21]:
arrnew[boolarr]

array([ 6,  7,  8,  9, 10])

In [22]:
#numpy operations

In [25]:
#array with array operation

walt = np.arange(0,10)
print(walt)
print(walt + walt)
print(walt * walt)
print(walt - walt)
print(walt / 4)
print(walt * 23)
print(walt / 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]
[  0  23  46  69  92 115 138 161 184 207]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [29]:
zeroarr = np.zeros(10)
zeroarr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
onearr  = np.ones(10)
onearr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
fivearr = np.ones(10)*5
fivearr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [33]:
randarr = np.arange(10,51)
randarr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [34]:
randeven = np.arange(10,51,2)
randeven

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [36]:
threematrix = np.arange(9).reshape(3,3)
threematrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
randnum = np.random.rand()
randnum

0.21156944716332138

In [39]:
randnumdist = np.random.randn(25)
randnumdist

array([ 1.44874358,  0.60372332,  0.76830775, -0.26170263, -0.55046921,
       -1.30382723, -1.1509308 , -2.36378854, -0.52821456, -0.96001536,
       -1.1975501 , -0.17214138,  0.78543264,  1.6002816 ,  1.30686428,
        0.4231777 ,  1.41662561,  1.4822996 ,  0.97829403,  0.94127668,
        1.44841685, -0.52190695, -0.60909676,  0.14369519,  0.46778545])

In [40]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [41]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [45]:
mat[3,4]

20

In [49]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [50]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
mat.sum()

325

In [52]:
np.sum(mat)

325

In [53]:
mat.std()

7.211102550927978

In [54]:
mat2 = np.arange(1,26).reshape(5,5)
mat2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
mat2.std()

7.211102550927978

In [57]:
mat2.sum(axis=1)

array([ 15,  40,  65,  90, 115])